name: Firebase App Distribution

on:
  push:
    branches: [dev-kemetx]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: mmf-dev

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build the APK
        run: |
          ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: firebase/firebase-action@v2
        with:
          token: ${{ secrets.FIREBASE_TOKEN }}  # Ensure this secret is set correctly
          app: ${{ secrets.FIREBASE_APP_ID }}   # The Firebase App ID from the Firebase Console
          groups: "kemetx-mobile-wallet"        # Optional: Specify groups of testers
          file: app/build/outputs/apk/prod/mifospay-android-prod-release.apk  # Verify APK path
          release-notes: "New release from GitHub Actions"  # Optional release notes
