name: Deploy APK to Firebase App Distribution

on:
  push:
    branches: [dev-kemetx]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mmf-dev
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase Service Account Credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase_credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase_credentials.json

      - name: Debug Service Account File
        run: cat firebase_credentials.json # Use with caution, for debugging only!

      - name: Verify Firebase Authentication
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase_credentials.json
        run: firebase projects:list

      - name: Build the APK
        run: ./gradlew assembleRelease # Update the path if necessary

      - name: Deploy APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase_credentials.json
        run: |
          firebase appdistribution:distribute \
            app/build/outputs/apk/prod/mifospay-android-prod-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "kemetx-mobile-wallet" \
            --release-notes "New release from GitHub Actions"
