name: Deploy APK to Firebase App Distribution

on:
  push:
    branches: [dev-kemetx]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mmf-dev
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > firebase_credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase_credentials.json
          firebase projects:list # Test authentication

      - name: Build the APK
        run: ./gradlew assembleRelease # Adjust if using a different build system

      - name: Deploy APK to Firebase App Distribution
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          firebase appdistribution:distribute \
            app/build/outputs/apk/prod/mifospay-android-prod-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "kemetx-mobile-wallet" \
            --release-notes "New release from GitHub Actions"
