name: Firebase App Distribution

on:
  push:
    branches: [dev-kemetx]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: mmf-dev

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build the APK
        run: |
          ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/firebase-action@v2
        with:
          api_token: ${{ secrets.FIREBASE_TOKEN}}
          app_file: app/build/outputs/apk/prod/mifospay-android-prod-release.apk
          track: beta
          groups: kemetx-mobile-wallet  # Optional: Specify groups of testers
