name: Firebase App Distribution

on:
  push:
    branches: [dev-kemetx]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: mmf-dev

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the APK
        run: |
          ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0  # Correct action
        with:
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}  # Your Firebase service account JSON key
          app: ${{ secrets.FIREBASE_APP_ID }}  # Firebase App ID
          groups: "kemetx-mobile-wallet"  # Optional: Specify groups of testers
          file: app/build/outputs/apk/prod/mifospay-android-prod-release.apk  # Path to APK
          release-notes: "New release from GitHub Actions"  # Optional release notes
